site_name: LayeredCompute
site_description: Multi-Layered Intelligence
site_url: https://www.layeredcompute.com

theme:
  name: mkdocs
  custom_dir: docs/overrides

nav:
  - Home: index.md
  - Bus Interface:
      - PCIe-Features:
          - Error Containment: pci-features/errcontain.md
          - Advanced Error Reporting: pci-features/aer.md
      - CXL: cxl.md

extra_css:
  - stylesheets/extra.css
