site_name: LayeredCompute
site_description: Multi-Layered Intelligence
site_url: https://www.layeredcompute.com

theme:
  name: mkdocs
  custom_dir: docs/overrides

nav:
  - Home: index.md
  - Bus Interface:
      - PCIe-Features:
          - Error Containment: pci-features/errcontain.md
          - Advanced Error Reporting: pci-features/aer.md
          - Multi-Segment: pci-features/multisegment.md
          - Posted - Non Posted Transactions: pci-features/p-np.md
          - MSI: pci-features/msi.md
          - Flit Mode: pci-features/flit.md
      - CXL: cxl.md

extra_css:
  - stylesheets/extra.css
